default:
  tags: 
  - interndevelopment

stages:
  - dev-build-docker-image
  - dev-container-image-scan
  - dev
  - dev-automate-api-nep

include:
   - '/build/ci/build.yml'
  #  - '/build/ci/ciss.yml'
   - '/build/ci/deploy-dev.yml'
  #  - '/build/ci/automate-api-nep.yml'*